spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: password

server:
    port: 8080

stripe:
  api:
    url: https://api.stripe.com
  enabled: true
  timeout: 5000
  currency: USD,CZK

payment:
  provider: paypal